### ISSUE TITLE
error message when trying to rename a "syntax word"

### ISSUE THREAD

**Issue by michaelbrusegard** [saecki/live-rename.nvim#1]
Hey, love the plugin btw! I get the error message below when I try to rename a word that is a part of the syntax (not a variable itself). For example when I try to rename the word `local` that is declaring a Lua variable. The plugin seems to still behave as expected it is just the error message that shows up.
```
Error  16:28:18 msg_show.lua_error Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/live-rename.nvim/lua/live-rename.lua:99: attempt to index local 'err' (a nil value)
stack traceback:
	...cal/share/nvim/lazy/live-rename.nvim/lua/live-rename.lua:99: in function 'handler'
	...m/HEAD-2a24d0a/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by saecki** [comment]
I've pushed a fix on main, before that the wrong server could be selected, which could have been an issue here.
And I've merged a PR that should at least raise an error when trying to show an error notification.

Can you check if that fixes you're issue?

**Comment by michaelbrusegard** [comment]
@saecki The error seems to be fixed now! Now it doesn't do anything if I am trying to rename something that is not expected by the LSP. It would maybe be nice to have some kind of fallback so it renames using grep maybe when it can't do it using the LSP. What do you think? That would be unrelated to this issue though :)

**Comment by saecki** [comment]
That is definitely out of scope for this plugin
