### ISSUE TITLE
Feature: save all edited buffers after rename

### ISSUE THREAD

**Issue by serhez** [saecki/live-rename.nvim#5]
When using LSP, it is possible that renaming a keyword (e.g., class name) may change the contents of many buffers. However, I noticed that these changes are not automatically saved. Could it be possible to save all affected buffers after a rename? Perhaps it could be an optional feature that can be turned on/off in the config.

Thanks!

**Comment by saecki** [comment]
Well  you could just make a function  like this:
```lua
local function rename_and_write(opts)
    require("live-rename").rename(opts)
    vim.cmd("wa")
end
```

**Comment by serhez** [comment]
This solution would save all buffers (even those that were not affected by the rename), so it's not 100% what I meant. But it's an easy solution and works in most cases, it makes sense to do it this way! Thank you for the reply :)

**Comment by saecki** [comment]
never mind that doesn't even work 😅

**Comment by serhez** [comment]
Yeah right, I just also noticed that we would need to use the `vim.cmd("wa")` command when some event is triggered after the rename takes place.

**Comment by saecki** [comment]
Yes, but this can easily be implemented outside this plugin for all `textDocument/rename` requests, so it should also work if you're just calling `vim.lsp.buf.rename()`:
```lua
    -- Write buffers that were edited
    local rename_handler = vim.lsp.handlers["textDocument/rename"]
    ---@param result lsp.WorkspaceEdit?
    vim.lsp.handlers["textDocument/rename"] = function(err, result, ctx, config)
        rename_handler(err, result, ctx, config)

        if err or not result then
            return
        end

        ---@param buf integer?
        local function write_buf(buf)
            if buf and vim.api.nvim_buf_is_valid(buf) and vim.api.nvim_buf_is_loaded(buf) then
                vim.api.nvim_buf_call(buf, function()
                    vim.cmd("w")
                end)
            end
        end
        if result.changes then
            for uri, edits in pairs(result.changes) do
                local buf = vim.uri_to_bufnr(uri)
                write_buf(buf)
            end
        elseif result.documentChanges then
            for _, change in ipairs(result.documentChanges) do
                local buf = vim.uri_to_bufnr(change.textDocument.uri)
                write_buf(buf)
            end
        end
    end
```

**Comment by saecki** [comment]
I would like to keep this plugin small and focused, so I'm not including this

**Comment by serhez** [comment]
That does the trick, thanks again :)
