### ISSUE TITLE
[help] What are the highlight group names? 

### ISSUE THREAD

**Issue by Ajaymamtora** [saecki/live-rename.nvim#7]
When renaming a word the foreground blends in with the background:
![image](https://github.com/user-attachments/assets/7f8e5c17-0304-4440-aa80-167f1257d638)

**Comment by saecki** [comment]
The default ones are `CurSearch` and `Search`, but you can also change them in the config:
```lua
require("live-rename").setup({
    hl = {
        current = "CurSearch",
        others = "Search",
    },
})
```
